.TH msm 1 "2017-08-09" "" "Mycroft Skill Manager"
.SH NAME
msm \- The Mycroft Skill Manager
.SH SYNOPSIS
.B msm
\fBoperation [\fIargument]

.B msm
\fBinstall \fBrss-skill

.SH DESCRIPTION
msm is a command line tool for installing and updating Mycroft skills. The command performs a number of operations including installing all default skills

.SH OPTIONS
.TP
\fBinstall \fIname\fR
Install the skill matching \fIname\fR found at https://github.com/MycroftAI/mycroft-skills
.TP
\fBinstall \fIgit-repository\fR
Install skill from the git repository \fIgit-repository\fR
.TP
\fBremove \fIname\fR
Remove the skill matching \fIname\fR
.TP
\fBupdate\fR
Update all installed skills to head of latest master branch
.TP
\fBdefault
Install and update all default skills
.TP
\fBlist
Lists available skills
.TP
\fBsearch \fIname\fR
Search for a skill in https://github.com/MycroftAI/mycroft-skills without installing it
.TP
