swagger: '2.0'
info:
  description: API used to communicate with Mycroft backend
  version: '1'
  title: Mycroft API
host: api.mycroft.ai
basePath: /v1
tags:
  - name: device
    description: Operations about device
schemes:
  - https
paths:
  /auth/token:
    get:
      tags:
        - device
      summary: Gets a fresh login session from a refresh token
      operationId: getRefreshToken
      security:
        - refresh_auth:
            - 'refresh:token'
  /device:
    post:
      tags:
        - device
      summary: Creates a device
      operationId: createDevice
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
    put:
      tags:
        - device
      summary: Updates an existent device
      operationId: updateDevice
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  /device/code:
    get:
      tags:
        - device
      summary: >-
        Generates a pairing code and associates with the state string passed as
        parameter
      operationId: generatePairingCode
  /device/activate:
    post:
      tags:
        - device
      summary: Activates a paired device
      operationId: activateDevice
  '/device/{uuid}':
    get:
      tags:
        - device
      summary: Finds device by uuid
      operationId: findDeviceByUuid
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
    patch:
      tags:
        - device
      summary: Performs a partial update over a device
      operationId: updateDevicePartial
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
    delete:
      tags:
        - device
      summary: Deletes a device
      operationId: deleteDeviceByUuid
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/setting':
    get:
      tags:
        - device
      summary: Finds the setting from a device
      operationId: findDeviceSetting
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/subscription':
    get:
      tags:
        - device
      summary: Finds the subscription of the user associated with the device
      operationId: findDeviceSubscription
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/location':
    get:
      tags:
        - device
      summary: Finds the device location
      operationId: findDeviceLocation
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/skill':
    get:
      tags:
        - device
      summary: Finds all skill associated with a device
      operationId: findDeviceSkills
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
    delete:
      tags:
        - device
      summary: Deletes a skill from a device
      operationId: deleteDeviceSkill
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
    put:
      tags:
        - device
      summary: Creates or updates a skill from a device
      operationId: createUpdateDeviceSkill
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/skillJson':
    put:
      tags:
        - device
      summary: Updates the skill json associated with the device
      operationId: uptDeviceSkillJson
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/voice':
    get:
      tags:
        - device
      summary: Finds a link to download a premium voice if user has a paid account
      operationId: getPremiumVoiceLink
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/metric':
    post:
      tags:
        - device
      summary: Pushes the metric passed as body to a metrics service
      operationId: sendMetric
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/message':
    put:
      tags:
        - device
      summary: Sends an email to the user associated with the device
      operationId: sendEmail
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
  '/device/{uuid}/userSkill':
    get:
      tags:
        - device
      summary: >-
        For a given device, fetch all skills with a given identifier associated
        with the user linked to the device
      operationId: getUserSkillsByIdentifier
      security:
        - device_auth:
            - 'write:device'
            - 'read:device'
securityDefinitions:
  user_auth:
    type: oauth2
    authorizationUrl: 'https://api.mycroft.ai/v1/auth/login'
    flow: implicit
    scopes:
      'write:user': modify user and entities associated with user
      'read:user': read user and entities associated with user
  device_auth:
    type: oauth2
    authorizationUrl: 'https://apy.mycroft.ai/v1/device/activate'
    flow: implicit
    scopes:
      'write:device': modify device and entities associated with device
      'read:device': read device  and entities associated with device
  refresh_auth:
    type: oauth2
    authorizationUrl: 'https://api.mycroft.ai/v1/auth/login'
    flow: implicit
    scopes:
      'refresh:token': get a new fresh token
  basic_auth:
    type: basic